markdown: rdiscount 
permalink: /:year/:month/:title 
title: KennyWorld
url: http://liujianfeng.github.com
subscribe: http://liujianfeng.github.com/feed
exclude: [ README.md, newpost.rb ]
domain: http://liujianfeng.github.com
author: KennyWorld
email: kennyworld2003@msn.com
auto: true
twitterID: 
duoshuoShortname:  liujianfeng